import React,{useEffect,useRef,useState,useCallback} from 'react';
import {ScrollView,View,Text,TextInput,TouchableOpacity,Share,StyleSheet,Alert} from 'react-native';
import {uuid} from 'expo-modules-core';
import {apiClient,ApiError} from '../services/apiClient';
import {useAuth} from '../contexts/AuthContext';

type Role='tenant'|'landlord';
type Talk={id:string;shareId?:string;viewerRole:Role;version:number;questions:string[];answers:string[];slots:string[];proposedTime:string|null;timeAccepted:boolean;expiresAt:string;inactive:boolean;cancelled:boolean;progress:string;canConfirm:boolean;accepted:Record<Role,boolean[]>;needsCheck:Record<Role,boolean[]>;conversationDone:Record<Role,boolean>;confirmed:Record<Role,boolean>};
type Item={id:string;key:string;shared:boolean;direction:string;progress:string;expiresAt:string;proposedTime:string|null;timeAccepted:boolean};
const labels:Record<string,string>={requested:'응답 대기',responded:'답변 있음',conversation_completed:'양측 대화 완료',confirmed:'양측 확인 완료',cancelled:'취소',expired:'만료'};
function iso(value:string){const time=new Date(value.trim().replace(' ','T'));if(!Number.isFinite(time.getTime()))throw new Error('시간을 YYYY-MM-DD HH:mm 형식으로 입력해주세요.');return time.toISOString()}
function local(value:string){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16).replace('T',' ')}
export default function ContractTalkScreen(){
 const {user}=useAuth();const [items,setItems]=useState<Item[]>([]),[talk,setTalk]=useState<Talk|null>(null),[endpoint,setEndpoint]=useState('');
 const [mode,setMode]=useState<'list'|'create'|'detail'>('list'),[email,setEmail]=useState(''),[time,setTime]=useState(''),[proposal,setProposal]=useState(''),[answers,setAnswers]=useState(['','','']);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[feedbackDone,setFeedbackDone]=useState(false);
 const key=useRef(uuid.v4()),sending=useRef(false);const role=talk?.viewerRole;
 const loadList=useCallback(async()=>{try{const r=await apiClient.get<{requests:Item[]}>('/contract-talk');setItems(r.requests)}catch(e){setItems([]);throw e}},[]);
 async function run(fn:()=>Promise<void>){if(sending.current)return;sending.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message);if(e instanceof ApiError&&[401,403,404,410].includes(e.status))setTalk(null)}finally{sending.current=false;setBusy(false)}}
 useEffect(()=>{void run(loadList)},[loadList]);
 async function open(item:Item){const url=`/contract-talk/${item.shared?'shared/':''}${item.key}`;await run(async()=>{const r=await apiClient.get<{talk:Talk}>(url);setEndpoint(url);setTalk(r.talk);setAnswers(r.talk.answers);setProposal(r.talk.proposedTime?local(r.talk.proposedTime):'');setTime(r.talk.slots.map(local).join('\n'));setMode('detail')})}
 async function change(action:Record<string,unknown>){if(!talk)return;await run(async()=>{try{const r=await apiClient.patch<{talk:Talk}>(endpoint,{version:talk.version,change:action});setTalk(r.talk)}catch(e){if(e instanceof ApiError&&e.status===409){const r=await apiClient.get<{talk:Talk}>(endpoint);setTalk(r.talk);setAnswers(r.talk.answers);setProposal(r.talk.proposedTime?local(r.talk.proposedTime):'')}throw e}})}
 async function safeChange(make:()=>Record<string,unknown>){try{await change(make())}catch(e){setError((e as Error).message)}}
 const button=(text:string,fn:()=>void,disabled=false)=><TouchableOpacity accessibilityRole="button" accessibilityLabel={text} disabled={busy||disabled} style={[styles.button,(busy||disabled)&&{opacity:0.4}]} onPress={fn}><Text>{text}</Text></TouchableOpacity>;
 const input=(label:string,value:string,set:(s:string)=>void,multiline=false,maxLength=500)=><View style={styles.section}><Text>{label}</Text><TextInput accessibilityLabel={label} style={styles.input} value={value} onChangeText={set} multiline={multiline} maxLength={maxLength} autoCapitalize="none" /></View>;
 const frozen=!talk||talk.inactive||talk.progress==='confirmed';
 return <ScrollView contentContainerStyle={styles.root} keyboardShouldPersistTaps="handled"><Text style={styles.title}>계약 전 대화 요청</Text><Text>답변과 시간은 당사자의 기록이며 사실 진위·법적 안전을 보장하지 않습니다. 대화에 개인정보·소득·세금 정보를 적지 마세요.</Text>{error&&<Text accessibilityRole="alert">{error}</Text>}
 {mode==='list'&&<><Text style={styles.title}>보낸·받은 요청</Text>{button('목록 새로고침',()=>void run(loadList))}{!items.length&&!busy&&<Text>보낸·받은 요청이 없습니다.</Text>}{items.map(i=><View key={i.id} style={styles.section}>{button(`${i.direction==='sent'?'보낸':'받은'} 요청 · ${labels[i.progress]}`,()=>void open(i))}<Text>만료 {new Date(i.expiresAt).toLocaleString()}</Text>{i.proposedTime&&<Text>{new Date(i.proposedTime).toLocaleString()} · {i.timeAccepted?'일정 합의':'확인 대기'}</Text>}</View>)}{user?.userType==='tenant'&&button('새 요청 만들기',()=>{key.current=uuid.v4();setEmail('');setTime('');setMode('create')})}</>}
 {mode==='create'&&<><Text>수리 연락 방법·입주 일정·추가 확인 사항을 질문합니다. 상대 계정 이메일을 확인하고 링크를 직접 전달하세요. 자동 메일은 보내지 않습니다.</Text>{input('상대 임대인의 계정 이메일',email,setEmail,false,254)}{input('가능한 시간 (YYYY-MM-DD HH:mm, 줄마다 최대 3개)',time,setTime,true)}{button('요청 만들기',()=>void run(async()=>{const r=await apiClient.post<{talk:Talk}>('/contract-talk',{recipientEmail:email,clientKey:key.current,slots:time.split('\n').filter(s=>s.trim()).map(iso)});setTalk(r.talk);setEndpoint(`/contract-talk/${r.talk.id}`);setMode('detail')}))}</>}
 {mode==='detail'&&talk&&<><Text style={styles.title}>{talk.cancelled?'취소':talk.inactive?'만료':labels[talk.progress]}</Text>{button('최신 내용 확인',()=>void run(async()=>{const r=await apiClient.get<{talk:Talk}>(endpoint);setTalk(r.talk);setAnswers(r.talk.answers);setProposal(r.talk.proposedTime?local(r.talk.proposedTime):'')}))}
 {role==='tenant'&&talk.shareId&&!talk.inactive&&button('공유 링크 직접 전달',()=>{void Share.share({message:`https://www.ipjuhae.com/contract-talk/shared/${talk.shareId}`}).catch(()=>setError('공유 창을 열지 못했습니다.'))})}
 <Text>가능한 시간: {talk.slots.map(t=>new Date(t).toLocaleString()).join(' / ')}</Text>
 {role==='tenant'&&talk.progress==='requested'&&!talk.inactive&&<>{input('요청 일정 수정 (YYYY-MM-DD HH:mm, 줄마다 최대 3개)',time,setTime,true)}{button('일정 저장',()=>void safeChange(()=>({action:'edit',slots:time.split('\n').filter(s=>s.trim()).map(iso)})))}</>}
 {talk.questions.map((q,i)=><View style={styles.section} key={q}><Text style={styles.bold}>{q}</Text><Text>{talk.answers[i]||'답변 대기'}</Text><Text>합의: 임차인 {talk.accepted.tenant[i]?'동의':'대기'} · 임대인 {talk.accepted.landlord[i]?'동의':'대기'}</Text><Text>추가 확인: {talk.needsCheck.tenant[i]||talk.needsCheck.landlord[i]?'필요':'표시 없음'}</Text>{talk.progress!=='requested'&&<>{button(`답변 ${i+1} ${talk.accepted[role!][i]?'합의 철회':'합의'}`,()=>void change({action:'accept',index:i,value:!talk.accepted[role!][i]}),frozen||!talk.answers[i])}{button(`답변 ${i+1} ${talk.needsCheck[role!][i]?'추가 확인 해소':'추가 확인 필요'}`,()=>void change({action:'check',index:i,value:!talk.needsCheck[role!][i]}),frozen)}</>}</View>)}
 {role==='landlord'&&!talk.inactive&&!talk.conversationDone.tenant&&!talk.conversationDone.landlord&&<>{answers.map((a,i)=>input(`답변 ${i+1}`,a,v=>setAnswers(old=>old.map((s,j)=>j===i?v:s)),true))}{input('제안 시간 (YYYY-MM-DD HH:mm)',proposal,setProposal)}{button('답변 저장',()=>void safeChange(()=>({action:'respond',answers,proposedTime:proposal?iso(proposal):null})),frozen)}</>}
 {talk.proposedTime&&<><Text>제안: {new Date(talk.proposedTime).toLocaleString()} · {talk.timeAccepted?'일정 합의':'확인 대기'}</Text>{role==='tenant'&&button(talk.timeAccepted?'일정 합의 철회':'제안 시간에 합의',()=>void change({action:'accept_time',value:!talk.timeAccepted}),frozen)}</>}
 {!talk.inactive&&talk.progress!=='requested'&&<><Text>대화 완료: 임차인 {talk.conversationDone.tenant?'완료':'대기'} · 임대인 {talk.conversationDone.landlord?'완료':'대기'}</Text><Text>확인 완료: 임차인 {talk.confirmed.tenant?'완료':'대기'} · 임대인 {talk.confirmed.landlord?'완료':'대기'}</Text>{button('내 대화 완료',()=>void change({action:'conversation_done'}),frozen||talk.conversationDone[role!])}{button('내 확인 완료',()=>void change({action:'confirm'}),frozen||!talk.canConfirm||talk.confirmed[role!])}{(talk.conversationDone.tenant||talk.conversationDone.landlord)&&button('정정 위해 대화 다시 열기',()=>void change({action:'reopen'}))}</>}
 {role==='tenant'&&!talk.inactive&&button('요청 취소',()=>Alert.alert('요청 취소','취소하면 상대가 더 이상 응답할 수 없습니다.',[{text:'돌아가기',style:'cancel'},{text:'취소하기',style:'destructive',onPress:()=>void change({action:'cancel'})}]))}</>}
 {mode!=='list'&&button('보낸·받은 요청으로 돌아가기',()=>void run(async()=>{setTalk(null);setMode('list');await loadList()}))}
 <View style={styles.section}><Text style={styles.bold}>불편한 점 알려주기</Text><Text>대화·소득·세금·연락처는 첨부하지 않습니다. 불편한 동작만 직접 설명해주세요.</Text>{feedbackDone?<Text>의견이 접수됐어요</Text>:<>{input('불편했던 동작',feedback,setFeedback,true,2000)}{button('의견 보내기',()=>void run(async()=>{await apiClient.post('/feature-requests',{message:feedback.trim(),source:'app'});setFeedbackDone(true);setFeedback('')}),!feedback.trim())}</>}</View>
 </ScrollView>
}
const styles=StyleSheet.create({root:{padding:20,gap:14,paddingBottom:40,backgroundColor:'#fbf6ef'},title:{fontSize:22,fontWeight:'700'},bold:{fontWeight:'700'},section:{gap:8,paddingVertical:12},input:{borderWidth:1,borderColor:'#aaa',borderRadius:8,padding:12,backgroundColor:'#fff'},button:{padding:14,borderWidth:1,borderColor:'#c2451f',borderRadius:8,backgroundColor:'#fff'}});
