export interface MockListing {
  id: number
  monthly_rent: number
  deposit: number
  address: string
  area_sqm: number
  floor: number
  photo_urls: string[]
  available_from: string
  property_type: string
  description: string | null
  region: string
}

export const mockListings: MockListing[] = [
  {
    id: 1,
    monthly_rent: 80,
    deposit: 500,
    address: '서울 강남구 역삼동 123',
    area_sqm: 33.5,
    floor: 3,
    photo_urls: [],
    available_from: '2026-04-01',
    property_type: 'oneroom',
    description: '역삼역 도보 5분, 풀옵션 원룸입니다.',
    region: '서울',
  },
  {
    id: 2,
    monthly_rent: 65,
    deposit: 300,
    address: '서울 마포구 합정동 45',
    area_sqm: 26.4,
    floor: 2,
    photo_urls: [],
    available_from: '2026-04-15',
    property_type: 'oneroom',
    description: '합정역 근처, 조용한 주거 환경.',
    region: '서울',
  },
  {
    id: 3,
    monthly_rent: 120,
    deposit: 1000,
    address: '서울 서초구 방배동 88',
    area_sqm: 52.0,
    floor: 5,
    photo_urls: [],
    available_from: '2026-05-01',
    property_type: 'apartment',
    description: '방배역 인근 아파트, 주차 가능.',
    region: '서울',
  },
  {
    id: 4,
    monthly_rent: 55,
    deposit: 200,
    address: '경기 성남시 분당구 정자동 200',
    area_sqm: 29.7,
    floor: 1,
    photo_urls: [],
    available_from: '2026-04-01',
    property_type: 'officetel',
    description: '정자역 도보 3분, 오피스텔.',
    region: '경기',
  },
  {
    id: 5,
    monthly_rent: 90,
    deposit: 700,
    address: '서울 용산구 한남동 17',
    area_sqm: 45.0,
    floor: 4,
    photo_urls: [],
    available_from: '2026-06-01',
    property_type: 'villa',
    description: '한남동 주택가, 한강 조망 가능.',
    region: '서울',
  },
  {
    id: 6,
    monthly_rent: 40,
    deposit: 100,
    address: '인천 남동구 구월동 33',
    area_sqm: 19.8,
    floor: 2,
    photo_urls: [],
    available_from: '2026-04-10',
    property_type: 'oneroom',
    description: '인천 구월동 원룸, 버스정류장 근처.',
    region: '인천',
  },
  {
    id: 7,
    monthly_rent: 150,
    deposit: 2000,
    address: '서울 강남구 청담동 9',
    area_sqm: 79.2,
    floor: 8,
    photo_urls: [],
    available_from: '2026-07-01',
    property_type: 'apartment',
    description: '청담동 고층 아파트, 남향, 채광 좋음.',
    region: '서울',
  },
  {
    id: 8,
    monthly_rent: 70,
    deposit: 400,
    address: '서울 은평구 불광동 56',
    area_sqm: 36.0,
    floor: 3,
    photo_urls: [],
    available_from: '2026-04-20',
    property_type: 'villa',
    description: '불광역 도보 7분, 빌라 2층.',
    region: '서울',
  },
  {
    id: 9,
    monthly_rent: 60,
    deposit: 250,
    address: '경기 수원시 팔달구 인계동 78',
    area_sqm: 30.5,
    floor: 2,
    photo_urls: [],
    available_from: '2026-05-15',
    property_type: 'officetel',
    description: '수원역 근처 오피스텔, 풀옵션.',
    region: '경기',
  },
  {
    id: 10,
    monthly_rent: 100,
    deposit: 800,
    address: '서울 성동구 성수동 112',
    area_sqm: 49.5,
    floor: 6,
    photo_urls: [],
    available_from: '2026-04-30',
    property_type: 'apartment',
    description: '성수역 도보 5분, 신축 아파트.',
    region: '서울',
  },
]
