export interface MockListing {
  id: number
  monthly_rent: number
  deposit: number
  address: string
  area_sqm: number
  floor: number
  bedrooms: number
  bathrooms: number
  photo_urls: string[]
  available_from: string
  property_type: string
  description: string | null
  region: string
  nearest_station: string
  commute_note: string
  tags: string[]
  match_score: number
}

export const mockListings: MockListing[] = [
  {
    id: 1,
    monthly_rent: 80,
    deposit: 500,
    address: '서울 강남구 역삼동 123',
    area_sqm: 33.5,
    floor: 3,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80'],
    available_from: '2026-04-01',
    property_type: 'oneroom',
    description: '역삼역 도보 5분, 풀옵션 원룸입니다.',
    region: '서울',
    nearest_station: '역삼역',
    commute_note: '강남 업무지구 10분',
    tags: ['풀옵션', '역세권', '즉시입주'],
    match_score: 96,
  },
  {
    id: 2,
    monthly_rent: 65,
    deposit: 300,
    address: '서울 마포구 합정동 45',
    area_sqm: 26.4,
    floor: 2,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80'],
    available_from: '2026-04-15',
    property_type: 'oneroom',
    description: '합정역 근처, 조용한 주거 환경.',
    region: '서울',
    nearest_station: '합정역',
    commute_note: '홍대입구 8분',
    tags: ['조용한 골목', '반려동물 상담', '채광'],
    match_score: 91,
  },
  {
    id: 3,
    monthly_rent: 120,
    deposit: 1000,
    address: '서울 서초구 방배동 88',
    area_sqm: 52.0,
    floor: 5,
    bedrooms: 2,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80'],
    available_from: '2026-05-01',
    property_type: 'apartment',
    description: '방배역 인근 아파트, 주차 가능.',
    region: '서울',
    nearest_station: '방배역',
    commute_note: '서초역 12분',
    tags: ['주차 가능', '엘리베이터', '남향'],
    match_score: 88,
  },
  {
    id: 4,
    monthly_rent: 55,
    deposit: 200,
    address: '경기 성남시 분당구 정자동 200',
    area_sqm: 29.7,
    floor: 1,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80'],
    available_from: '2026-04-01',
    property_type: 'officetel',
    description: '정자역 도보 3분, 오피스텔.',
    region: '경기',
    nearest_station: '정자역',
    commute_note: '판교 7분',
    tags: ['역세권', '보안', '관리비 저렴'],
    match_score: 93,
  },
  {
    id: 5,
    monthly_rent: 90,
    deposit: 700,
    address: '서울 용산구 한남동 17',
    area_sqm: 45.0,
    floor: 4,
    bedrooms: 2,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80'],
    available_from: '2026-06-01',
    property_type: 'villa',
    description: '한남동 주택가, 한강 조망 가능.',
    region: '서울',
    nearest_station: '한강진역',
    commute_note: '이태원 6분',
    tags: ['한강 조망', '테라스', '저층 주거지'],
    match_score: 86,
  },
  {
    id: 6,
    monthly_rent: 40,
    deposit: 100,
    address: '인천 남동구 구월동 33',
    area_sqm: 19.8,
    floor: 2,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&q=80'],
    available_from: '2026-04-10',
    property_type: 'oneroom',
    description: '인천 구월동 원룸, 버스정류장 근처.',
    region: '인천',
    nearest_station: '인천터미널역',
    commute_note: '구월 상권 5분',
    tags: ['합리적 월세', '버스 인접', '수납공간'],
    match_score: 82,
  },
  {
    id: 7,
    monthly_rent: 150,
    deposit: 2000,
    address: '서울 강남구 청담동 9',
    area_sqm: 79.2,
    floor: 8,
    bedrooms: 3,
    bathrooms: 2,
    photo_urls: ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&q=80'],
    available_from: '2026-07-01',
    property_type: 'apartment',
    description: '청담동 고층 아파트, 남향, 채광 좋음.',
    region: '서울',
    nearest_station: '청담역',
    commute_note: '압구정로데오 9분',
    tags: ['고층', '남향', '가족 추천'],
    match_score: 84,
  },
  {
    id: 8,
    monthly_rent: 70,
    deposit: 400,
    address: '서울 은평구 불광동 56',
    area_sqm: 36.0,
    floor: 3,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=1200&q=80'],
    available_from: '2026-04-20',
    property_type: 'villa',
    description: '불광역 도보 7분, 빌라 2층.',
    region: '서울',
    nearest_station: '불광역',
    commute_note: '광화문 18분',
    tags: ['채광', '재래시장 인접', '분리형'],
    match_score: 80,
  },
  {
    id: 9,
    monthly_rent: 60,
    deposit: 250,
    address: '경기 수원시 팔달구 인계동 78',
    area_sqm: 30.5,
    floor: 2,
    bedrooms: 1,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80'],
    available_from: '2026-05-15',
    property_type: 'officetel',
    description: '수원역 근처 오피스텔, 풀옵션.',
    region: '경기',
    nearest_station: '수원시청역',
    commute_note: '수원역 11분',
    tags: ['풀옵션', '상권 인접', '보안'],
    match_score: 78,
  },
  {
    id: 10,
    monthly_rent: 100,
    deposit: 800,
    address: '서울 성동구 성수동 112',
    area_sqm: 49.5,
    floor: 6,
    bedrooms: 2,
    bathrooms: 1,
    photo_urls: ['https://images.unsplash.com/photo-1560448075-bb485b067938?w=1200&q=80'],
    available_from: '2026-04-30',
    property_type: 'apartment',
    description: '성수역 도보 5분, 신축 아파트.',
    region: '서울',
    nearest_station: '성수역',
    commute_note: '건대입구 6분',
    tags: ['신축', '카페거리', '엘리베이터'],
    match_score: 94,
  },
]
